### ISSUE TITLE
Link in IANA media type registration seems to contain a dead link

### ISSUE THREAD

**Issue by RingoDev** [spdx/spdx-spec#1158]
Taking a look at the [application/spdx+json](https://www.iana.org/assignments/media-types/application/spdx+json) entry published by IANA there is a reference included to https://github.com/spdx/spdx-spec/blob/master/schemas/spdx-schema.json which is no longer valid. 

This is not the case for the [text/spdx](https://www.iana.org/assignments/media-types/text/spdx) registration 
which doesn't link to the github repo but rather to the webpage at https://spdx.github.io/spdx-spec/ so maybe that would be a better way to go about it?

I wasn't sure where to raise this, so here I am creating this issue hoping to find somebody who knows how to amend such a registration entry.

**Comment by goneall** [comment]
Thanks @RingoDev for reporting this.

I looks like we broke this when we published SPDX 3.0.0.

I don't think we have the JSON schema published on github.io, but we could point to the spec itself.

We could update the URL to the branch location of the schema: https://github.com/spdx/spdx-spec/blob/support/2.3/schemas/spdx-schema.json

@rnjudge - thoughts?

**Comment by bact** [comment]
<s>We no longer have the `master` branch, so even have recreated the `schemas` directory and put the file `spdx-schema.json` to it, the URL will still not working as the URL `https://github.com/spdx/spdx-spec/blob/master/schemas/spdx-schema.json` has the `master` part in it.</s>

Correction 24 Apr 2026: I have tried the URL and found that GitHub redirected it to `main`. So the addition of `schemas` dir will work.

**Comment by bact** [comment]
Does it possible to update the URL in the IANA entry?

We might also need to have a new entry for SPDX 3 JSON as well? Or we can just share the existing `spdx+json`?

**Comment by bact** [comment]
PR https://github.com/spdx/spdx-spec/pull/1389 is proposed to fix this issue.
